# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AIChatUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

import requests
from PyQt5 import QtCore, QtWidgets, QtGui


class Ui_mainWindow(object):
    answer = ''

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(621, 412)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("aiui.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.ModelBox = QtWidgets.QComboBox(mainWindow)
        self.ModelBox.setGeometry(QtCore.QRect(310, 10, 301, 21))
        self.ModelBox.setObjectName("ModelBox")
        self.Input = QtWidgets.QTextEdit(mainWindow)
        self.Input.setGeometry(QtCore.QRect(10, 330, 551, 71))
        self.Input.setObjectName("Input")
        self.Submit = QtWidgets.QPushButton(mainWindow)
        self.Submit.setGeometry(QtCore.QRect(570, 330, 41, 31))
        self.Submit.setObjectName("Submit")
        self.APIURL = QtWidgets.QLineEdit(mainWindow)
        self.APIURL.setGeometry(QtCore.QRect(10, 10, 291, 20))
        self.APIURL.setObjectName("APIURL")
        self.AIRecive = QtWidgets.QTextBrowser(mainWindow)
        self.AIRecive.setGeometry(QtCore.QRect(10, 40, 601, 281))
        self.AIRecive.setObjectName("AIRecive")

        self.retranslateUi(mainWindow)
        self.Submit.clicked.connect(self.In)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "AIChatUI"))
        self.ModelBox.addItem('模型')
        try:
            with open('model.txt', 'r', encoding='utf-8') as f:
                for model in f:
                    model = model.strip()
                    if model:
                        self.ModelBox.addItem(model)
        except:
            with open('model.txt', 'a', encoding='utf-8') as f:
                pass
            self.AIRecive.setText("请在model文件夹中添加已经拥有的模型名字")
        self.Input.setPlaceholderText(_translate("mainWindow", "从这里开始聊天："))
        self.Submit.setText(_translate("mainWindow", "发送"))
        self.APIURL.setPlaceholderText(_translate("mainWindow", "API:http://127.0.0.1:11434/api/chat"))
        self.AIRecive.setPlaceholderText(_translate("mainWindow", "AI回复："))

    def In(self):
        words = self.Input.toPlainText()
        if words == '':
            self.AIRecive.append('输入不能为空\n')
            return
        model = self.ModelBox.currentText()
        if model == '模型':
            self.AIRecive.append('请选择模型\n')
            return
        self.Input.clear()
        time,answer = self.OutPut(words, model)
        with open('log.txt', 'a', encoding='utf-8') as f:
            f.write(time+' '+words+'\n'+answer+'\n')
            f.close()
        self.AIRecive.append(answer+'\n')

    def OutPut(self, words : str, model: str) -> tuple[str, str]:
        url = "http://127.0.0.1:11434/api/chat"
        url1 = self.APIURL.displayText()
        if url1 != '':
            url = url1
        data = {
            "model": model,
            "messages": [{"role": "user",
                          "content": words
                          }],
            "stream": False
        }
        try:
            r = requests.post(url, json=data)
            return r.json()['created_at'], r.json()['message']['content']
        except:
            return "000", 'Error'

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())